// This file is auto-generated. Do not edit manually.
import { ConfigManager } from './manager';
export const configManager = new ConfigManager({
  items: [
    {
      key: 'Equip_3_DefaultWeapon',
      InitInStorage: '',
      description: '',
      name: 'Hilt Temporary',
      type: 8192,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_39_BrownGreen 1000 Fans',
      InitInStorage: '',
      description: '',
      name: 'BrownGreen 1000 Fans Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_38_BlackBrown 1000 Fans',
      InitInStorage: '',
      description: '',
      name: 'BlackBrown 1000 Fans Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_37_WhiteBlue 1000 Fans',
      InitInStorage: '',
      description: '',
      name: 'WhiteBlue 1000 Fans Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_4_Purple',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_4_Purple',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_5_Halloween Wind Breaker',
      InitInStorage: '',
      description: '',
      name: 'Halloween Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_5_Red',
      InitInStorage: 'True',
      description: '',
      name: 'Red Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_1_Blue',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_5_Red',
      InitInStorage: 'True',
      description: '',
      name: 'Red Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_6_Yellow',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_2_Green',
      InitInStorage: 'True',
      description: '',
      name: 'Green Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Sprint_7_Orange',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Wind Breaker VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_6_Yellow',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_3_Orange',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_1_Blue',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_2_Green',
      InitInStorage: 'True',
      description: '',
      name: 'Green Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Trail_7_Halloween',
      InitInStorage: '',
      description: '',
      name: 'Halloween Trail VFX',
      type: 16388,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_1_Blue Default',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Default Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_11_Zombie',
      InitInStorage: '',
      description: '',
      name: 'Halloween Zombie Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_9_BrownGreen 1000FansSkin',
      InitInStorage: '',
      description: '',
      name: 'BrownGreen 1000 Fans Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_6_Yellow Default',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Default Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_2_Green Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Default Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_8_WhiteBlue 1000FansSkin',
      InitInStorage: '',
      description: '',
      name: 'WhiteBlue 1000 Fans Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_3_Orange Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Default Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_5_Red Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Default Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_4_Purple Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Default Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_7_BlackBrown 1000FansSkin',
      InitInStorage: '',
      description: '',
      name: 'BlackBrown 1000 Fans Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Body_10_SkinFossli',
      InitInStorage: '',
      description: '',
      name: 'Halloween Dino Body',
      type: 16387,
      packagedSIze: 0.1,
    },
    {
      key: 'Eyes_2_Pumkin',
      InitInStorage: '',
      description: '',
      name: 'Black Square Eye',
      type: 16486,
      packagedSIze: 0.1,
    },
    {
      key: 'Eyes_1_Goofy',
      InitInStorage: '',
      description: '',
      name: 'Goofy Eye',
      type: 16486,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_43_Zombie',
      InitInStorage: '',
      description: '',
      name: 'Halloween Zombie Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_42_Skin Fossl',
      InitInStorage: '',
      description: '',
      name: 'Halloween Dino Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_19_Blue Water-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Water-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_25_Blue Fire-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Fire-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_1_Blue Cube-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Cube-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_31_Blue Pentagon-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Pentagon-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_13_Blue Triangle-Shape Default Head',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Triangle-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_7_Blue Round-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Blue Round-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_9_Orange Round-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Round-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_15_Orange Triangle-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Triangle-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_33_Orange Pentagon-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Pentagon-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_3_Orange Cube-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Cube-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_27_Orange Fire-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Fire-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_21_Orange Water-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Orange Water-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_22_Purple Water-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Water-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_28_Purple Fire-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Fire-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_4_Purple Cube-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Cube-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_34_Purple Pentagon-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Pentagon-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_16_Purple Triangle-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Triangle-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_10_Purple Round-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Purple Round-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_8_Green Round-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Round-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_14_Green Triangle-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Triangle-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_32_Green Pentagon-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Pentagon-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_2_Green Cube-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Cube-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_26_Green Fire-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Fire-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_20_Green Water-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Green Water-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_30_Yellow Fire-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Fire-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_24_Yellow Water-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Water-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_6_Yellow Cube-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Cube-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_18_Yellow Triangle-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Triangle-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_36_Yellow Pentagon-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Pentagon-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_12_Yellow Round-Shape Default Head',
      InitInStorage: 'True',
      description: '',
      name: 'Yellow Round-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_11_Red Round-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Round-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_35_Red Pentagon-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Pentagon-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_17_Red Triangle-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Triangle-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_5_Red Cube-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Cube-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_23_Red Water-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Water-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_29_Red Fire-Shape Default',
      InitInStorage: 'True',
      description: '',
      name: 'Red Fire-Shape Default Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_41_Pumpkin',
      InitInStorage: '',
      description: '',
      name: 'Pumpkin Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Head_40_Goofy',
      InitInStorage: '',
      description: '',
      name: 'Goofy Head',
      type: 16385,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_1_Battery',
      InitInStorage: '',
      description: '',
      name: 'Energy Star',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_16_Tube',
      InitInStorage: '',
      description: '',
      name: 'Walkie-Talkie',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_15_TrialStone',
      InitInStorage: '',
      description: '',
      name: 'Friend Stone',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_10_Pen',
      InitInStorage: '',
      description: '',
      name: 'Color Crystal',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_6_EnergyContainerS',
      InitInStorage: '',
      description: '',
      name: 'Energy Pack (Small)',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_5_EnergyContainerM',
      InitInStorage: '',
      description: '',
      name: 'Energy Pack (Medium)',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_4_EnergyContainerL',
      InitInStorage: '',
      description: '',
      name: 'Energy Pack (Large)',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_13_SpeedContainerS',
      InitInStorage: '',
      description: '',
      name: 'Boost Engine (Small)',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_12_SpeedContainerM',
      InitInStorage: '',
      description: '',
      name: 'Boost Engine (Medium)',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_11_SpeedContainerL',
      InitInStorage: '',
      description: '',
      name: 'Boost Engine (Large)',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_7_GlideModule',
      InitInStorage: '',
      description: '',
      name: 'Glide Module',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_14_SprintModule',
      InitInStorage: '',
      description: '',
      name: 'Dash Module',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'Equip_9_OverloadModule',
      InitInStorage: '',
      description: '',
      name: 'Overload Module',
      type: 4096,
      packagedSIze: 0.1,
    },
    {
      key: 'sc',
      InitInStorage: '',
      description: '',
      name: 'SC',
      type: 32768,
      packagedSIze: 0.1,
    },
    {
      key: 'ss',
      InitInStorage: '',
      description: '',
      name: 'SS',
      type: 32768,
      packagedSIze: 0.1,
    },
  ],
  store: [
    {
      key: 'Pumpkin Head',
      gain: {
        Head_41_Pumpkin: 1,
      },
      cost: {
        ss: 1000,
      },
    },
    {
      key: 'Boost Engine Small',
      gain: {
        Equip_13_SpeedContainerS: 1,
      },
      cost: {
        ss: 50,
      },
    },
    {
      key: 'Boost Engine Medium',
      gain: {
        Equip_12_SpeedContainerM: 1,
      },
      cost: {
        ss: 100,
      },
    },
    {
      key: 'Boost Engine (Large)',
      gain: {
        Equip_11_SpeedContainerL: 1,
      },
      cost: {
        ss: 200,
      },
    },
    {
      key: 'Energy Pack (Small)',
      gain: {
        Equip_6_EnergyContainerS: 1,
      },
      cost: {
        ss: 20,
      },
    },
    {
      key: 'Energy Pack (Medium)',
      gain: {
        Equip_5_EnergyContainerM: 1,
      },
      cost: {
        ss: 50,
      },
    },
    {
      key: 'Energy Pack (Large)',
      gain: {
        Equip_4_EnergyContainerL: 1,
      },
      cost: {
        ss: 150,
      },
    },
    {
      key: 'Glide Module',
      gain: {
        Equip_7_GlideModule: 1,
      },
      cost: {
        ss: 100,
      },
    },
    {
      key: 'Dash Module',
      gain: {
        Equip_14_SprintModule: 1,
      },
      cost: {
        ss: 150,
      },
    },
    {
      key: 'Overload Module',
      gain: {
        Equip_9_OverloadModule: 1,
      },
      cost: {
        ss: 150,
      },
    },
    {
      key: 'Color Crystal',
      gain: {
        Equip_10_Pen: 1,
      },
      cost: {
        ss: 5,
      },
    },
    {
      key: 'Walkie-Talkie',
      gain: {
        Equip_16_Tube: 1,
      },
      cost: {
        ss: 20,
      },
    },
    {
      key: 'Friend Stone',
      gain: {
        Equip_15_TrialStone: 1,
      },
      cost: {
        ss: 50,
      },
    },
    {
      key: 'Goofy Head Eye',
      gain: {
        Head_40_Goofy: 1,
        Eyes_1_Goofy: 1,
      },
      cost: {
        ss: 1200,
      },
    },
    {
      key: 'Halloween Trail VFX',
      gain: {
        Trail_7_Halloween: 1,
      },
      cost: {
        ss: 500,
      },
    },
  ],
  archievementTask: [
    {
      Name: 'Tutorial',
      Type: 'once',
      Award: {
        ss: 100,
      },
      Condition: 'tutoral',
    },
    {
      Name: 'Fly200',
      Type: 'once',
      Award: {
        ss: 200,
      },
      Condition: 'fly.meters > 200',
    },
    {
      Name: 'AddFriend1',
      Type: 'once',
      Award: {
        ss: 200,
      },
      Condition: 'friends.count > 1',
    },
    {
      Name: 'KilledSpider25',
      Type: 'once',
      Award: {
        ss: 200,
      },
      Condition: 'pve.monsters.Spider > 25',
    },
    {
      Name: 'BreakBlade50',
      Type: 'once',
      Award: {
        ss: 200,
      },
      Condition: 'blades.breakTimes > 50',
    },
    {
      Name: 'UpgradeArm50',
      Type: 'once',
      Award: {
        ss: 500,
      },
      Condition: 'blades.maxLevel > 5',
    },
    {
      Name: 'PurchaseHilt1',
      Type: 'once',
      Award: {
        ss: 300,
      },
      Condition: 'purchases.hilt > 1',
    },
    {
      Name: 'DrawBlade1',
      Type: 'once',
      Award: {
        ss: 100,
      },
      Condition: 'blades.count > 5',
    },
    {
      Name: 'UpgradeArmLv10',
      Type: 'once',
      Award: {
        ss: 500,
      },
      Condition: 'blade.maxLevel > 10',
    },
    {
      Name: 'KilledWoodGuardian10',
      Type: 'once',
      Award: {
        ss: 200,
      },
      Condition: 'pve.monsters[”Wood Guardian”] > 10',
    },
    {
      Name: 'KilledMimicChest1',
      Type: 'once',
      Award: null,
      Condition: 'pve.monsters[”Mimic Chest”] > 1',
    },
    {
      Name: 'DefeatSpiritborne5',
      Type: 'once',
      Award: {
        ss: 200,
      },
      Condition: 'pvp.killed > 5',
    },
    {
      Name: 'KilledBoss1',
      Type: 'once',
      Award: {
        ss: 1000,
      },
      Condition: 'pve.bossKilled > 1',
    },
    {
      Name: 'UpgradeArm30',
      Type: 'once',
      Award: {
        ss: 1000,
      },
      Condition: 'blades.maxLevel > 30',
    },
    {
      Name: 'OwnSeasonLimitedWeapon1',
      Type: 'once',
      Award: null,
      Condition: 'blades.seasonLimitedCount > 1',
    },
    {
      Name: 'KilledMonsters10',
      Type: 'daily',
      Award: {
        ss: 200,
      },
      Condition: 'pve.dailyKilled > 10',
    },
    {
      Name: 'DefeatSpiritborne5',
      Type: 'daily',
      Award: {
        ss: 200,
      },
      Condition: 'pvp.dailyCount > 10',
    },
    {
      Name: 'Fly500',
      Type: 'daily',
      Award: {
        ss: 200,
      },
      Condition: 'fly.meters > 500',
    },
    {
      Name: 'KilledBoss10',
      Type: 'longterm',
      Award: null,
      Condition: 'pve.bossKilled > 10',
    },
    {
      Name: 'OwnArmLv30_10',
      Type: 'longterm',
      Award: null,
      Condition: 'blades.lv30Count > 10',
    },
    {
      Name: 'AddFriend100',
      Type: 'longterm',
      Award: null,
      Condition: 'friends.count > 100',
    },
  ],
  monsters: [
    {
      Name: 'Cosmo Devour',
      Type: 'Boss',
    },
    {
      Name: 'Mimic Chest',
      Type: 'Medium',
    },
    {
      Name: 'Wood Guardian',
      Type: 'Medium',
    },
    {
      Name: 'Venom Bee',
      Type: 'Small',
    },
    {
      Name: 'Spider',
      Type: 'Small',
    },
    {
      Name: 'Glaciron, the Frostveil Serpent',
      Type: 'Boss',
    },
    {
      Name: 'Frostshade Wraith',
      Type: 'Medium',
    },
    {
      Name: 'Snowbound Guardian',
      Type: 'Large',
    },
    {
      Name: 'Frostfang Wolf',
      Type: 'Medium',
    },
    {
      Name: 'Corvyn Bat',
      Type: 'Small',
    },
  ],
});
